// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApp.Data;

#nullable disable

namespace TodoApp.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    partial class TodoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("TodoApp.Models.Todo", b =>
                {
                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Title");

                    b.ToTable("Todo");

                    b.HasData(
                        new
                        {
                            Title = "Play basketball",
                            IsCompleted = true
                        },
                        new
                        {
                            Title = "Shopping",
                            IsCompleted = false
                        },
                        new
                        {
                            Title = "Assignment",
                            IsCompleted = true
                        },
                        new
                        {
                            Title = "Workout",
                            IsCompleted = false
                        },
                        new
                        {
                            Title = "Make food",
                            IsCompleted = false
                        },
                        new
                        {
                            Title = "Cleaning",
                            IsCompleted = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
